name: pyramid-phoenix
channels:
  - conda-forge
dependencies:
  - pip
  - python=3.12
  - setuptools
  - curl
  - pyopenssl
  - cryptography
  - icu
# tests
  - pytest
  - flake8
  - pycodestyle
# phoenix
  - nginx
  - supervisor
  - gunicorn
  - requests-oauthlib
  - gevent
  - lxml
  - mako
  - dateparser
  - python-dateutil
  - requests
  - pyyaml
  - pygments
  - pytz
  - owslib
  - transaction
  - genshi
  - pyjwt
# celery
  - celery
  - kombu
# mongodb
  - pymongo
  - mongodb

